// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"gitlab.com/golang-hse-2022/team1/tasks/client/handler"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationHandlerApproveCmd returns a cmd to handle operation approve
func makeOperationHandlerApproveCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "Approve",
		Short: `Approve task by taskId in case it has been assigned to the user`,
		RunE:  runOperationHandlerApprove,
	}

	if err := registerOperationHandlerApproveParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationHandlerApprove uses cmd flags to call endpoint api
func runOperationHandlerApprove(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := handler.NewApproveParams()
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationHandlerApproveResult(appCli.Handler.Approve(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationHandlerApproveParamFlags registers all flags needed to fill params
func registerOperationHandlerApproveParamFlags(cmd *cobra.Command) error {
	return nil
}

// parseOperationHandlerApproveResult parses request result and return the string content
func parseOperationHandlerApproveResult(resp0 *handler.ApproveOK, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning approveOK is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*handler.ApproveBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*handler.ApproveForbidden)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*handler.ApproveInternalServerError)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response approveOK is not supported by go-swagger cli yet.

	return "", nil
}
