// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"gitlab.com/golang-hse-2022/team1/tasks/client/handler"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationHandlerDeclineCmd returns a cmd to handle operation decline
func makeOperationHandlerDeclineCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "Decline",
		Short: `Decline task by taskId in case it has been assigned to the user`,
		RunE:  runOperationHandlerDecline,
	}

	if err := registerOperationHandlerDeclineParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationHandlerDecline uses cmd flags to call endpoint api
func runOperationHandlerDecline(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := handler.NewDeclineParams()
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationHandlerDeclineResult(appCli.Handler.Decline(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationHandlerDeclineParamFlags registers all flags needed to fill params
func registerOperationHandlerDeclineParamFlags(cmd *cobra.Command) error {
	return nil
}

// parseOperationHandlerDeclineResult parses request result and return the string content
func parseOperationHandlerDeclineResult(resp0 *handler.DeclineOK, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning declineOK is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*handler.DeclineBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*handler.DeclineForbidden)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*handler.DeclineInternalServerError)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response declineOK is not supported by go-swagger cli yet.

	return "", nil
}
