// Code generated by go-swagger; DO NOT EDIT.

package handler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeclineParams creates a new DeclineParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeclineParams() *DeclineParams {
	return &DeclineParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeclineParamsWithTimeout creates a new DeclineParams object
// with the ability to set a timeout on a request.
func NewDeclineParamsWithTimeout(timeout time.Duration) *DeclineParams {
	return &DeclineParams{
		timeout: timeout,
	}
}

// NewDeclineParamsWithContext creates a new DeclineParams object
// with the ability to set a context for a request.
func NewDeclineParamsWithContext(ctx context.Context) *DeclineParams {
	return &DeclineParams{
		Context: ctx,
	}
}

// NewDeclineParamsWithHTTPClient creates a new DeclineParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeclineParamsWithHTTPClient(client *http.Client) *DeclineParams {
	return &DeclineParams{
		HTTPClient: client,
	}
}

/*
DeclineParams contains all the parameters to send to the API endpoint

	for the decline operation.

	Typically these are written to a http.Request.
*/
type DeclineParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the decline params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeclineParams) WithDefaults() *DeclineParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the decline params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeclineParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the decline params
func (o *DeclineParams) WithTimeout(timeout time.Duration) *DeclineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the decline params
func (o *DeclineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the decline params
func (o *DeclineParams) WithContext(ctx context.Context) *DeclineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the decline params
func (o *DeclineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the decline params
func (o *DeclineParams) WithHTTPClient(client *http.Client) *DeclineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the decline params
func (o *DeclineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeclineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
